#!/usr/bin/env bash

if [ -f "./.env" ]; then
  source ./.env
fi

# Suppress output
BLACKHOLE="$(./worker)"

if [ "${CONTAINER_NAME}" == "" ]; then
  CONTAINER_NAME="$(basename "$(cd .. && pwd)")-$(basename "$(pwd)")"
fi

WORKER_NAME="${CONTAINER_NAME}-worker"

docker exec -it "${WORKER_NAME}" console "$@"
